# Generated by Django 5.1.4 on 2025-01-18 19:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("place", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기중"),
                            ("ACCEPTED", "수락됨"),
                            ("REJECTED", "거절됨"),
                            ("CANCELED", "취소됨"),
                            ("COMPLETED", "완료"),
                        ],
                        max_length=100,
                    ),
                ),
                ("origin_text", models.TextField(null=True)),
                ("summary", models.TextField(null=True)),
            ],
            options={
                "db_table": "appointment",
            },
        ),
    ]
