# Generated by Django 5.1.4 on 2025-01-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="end_date",
            field=models.DateTimeField(default="2025-01-19 00:00:00", null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="start_date",
            field=models.DateTimeField(default="2025-01-19 00:00:00", null=True),
        ),
    ]
