# Generated by Django 5.1.4 on 2025-01-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_available_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
