# Generated by Django 5.1.4 on 2025-01-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_smsauthcode_user_birth_user_career_user_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="credithistory",
            name="available_date",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="category",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("S", "Senior"), ("J", "Junior"), ("A", "Admin")],
                max_length=100,
                null=True,
            ),
        ),
    ]
